inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 2.6
  Exclude:
    - gemfiles/*
    - spec/dummy/**/*

Lint/MissingSuper:
  Exclude:
    - lib/ok_computer/checks/*

Metrics/BlockLength:
  Exclude:
    - spec/ok_computer/*
    - okcomputer-checks.gemspec

Naming/FileName:
  Exclude:
    - lib/okcomputer-checks.rb

## TODOs

Style/Documentation:
  Enabled: false
